name: translations_cleaner
description: Package to remove unused keys in arb files, across all translations
version: 0.0.5
repository: https://github.com/Chinmay-KB/translations_cleaner

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  args: ^2.3.1
  glob: ^2.1.0
  yaml: ^3.1.3

dev_dependencies:
  test: ^1.26.3
  lints: ^6.0.0
